name: "Deploy and Release"

on:
  push:
    branches: [ "master" ]

env:
  PROJECT_PATH: .

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: dotnet restore ${{ env.PROJECT_PATH }} --runtime win-x64

      - run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release

      - run: dotnet workload list

      - run: dotnet publish ${{ env.PROJECT_PATH }} --configuration Release -p:PublishSingleFile=true -p:SelfContained=true -p:RuntimeIdentifier=win-x64
