name: "Deploy and Release"

permissions: write-all

on:
  push:
    tags:
      - 'v*'

env:
  PROJECT_PATH: .

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: .NET Restore Dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }} --runtime win-x64

      - name: .NET Build
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release

      - name: .NET Publish
        run: dotnet publish ${{ env.PROJECT_PATH }} --configuration Release -p:PublishSingleFile=true -p:SelfContained=true -p:RuntimeIdentifier=win-x64

      - name: Create GitHub release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "${{ github.event.repository.name }}-${{ github.ref_name }}"
          draft: false
          prerelease: false

      - name: Proper name for exe
        run: |
          $newFileName = "${{ github.event.repository.name }}-${{ github.ref_name }}.exe"
          Rename-Item -Path "bin/Release/net9.0-windows/win-x64/publish/rex.exe" -NewName $newFileName

      - name: Add exe to GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/Release/net9.0-windows/win-x64/publish/${{ github.event.repository.name }}-${{ github.ref_name }}.exe
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: false
